site_name: SieveComP
site_description: Automate and standardize seismic catalog processing from SeisComP.
repo_url: https://github.com/KenethGarcia/SieveComP
repo_name: KenethGarcia/SieveComP

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]