[settings]
event_type_column = "event_type"
time_column = "time_value"
author_column = "creationInfo_author"

[[database]]
name       = "sc6"
env_file   = ".env"
env_prefix = "SERVER_SC6"

[[queries]]
name       = "sc6"
sql_file   = "./queries/revision.sql"
description= "Query to retrieve events from SeisComP6 database"
database   = "sc6"

[[polygons]]
name        = "local_area"
path        = "/home/keneth/Documents/Academic_Projects/Revision_Sismicidad_SGC/src/data/polygons/SGC/RSNC/arealocal.txt"
description = "Local area region from Colombia"

[[polygons]]
name        = "vmm"
path        = "/home/keneth/Documents/Academic_Projects/Revision_Sismicidad_SGC/src/data/polygons/SGC/RSNC/VMM.txt"
description = "VMM region - MLr_vmm"

[[polygons]]
name        = "nll"
path        = "/home/keneth/Documents/Academic_Projects/Revision_Sismicidad_SGC/src/data/polygons/SGC/RSNC/NLL.txt"
description = "NonLinLoc region - NLL"

#[[duplicates]]
#name           = "General duplicate search"
#description    = "Detect near-identical events by time and distance proximity"
#method         = "sswa"                     # "adjacent" or "sswa"
#event_type     = ["earthquake", "volcanic eruption", "explosion", "outside of network interest"]
#subset         = ["time_value", "latitude_value", "longitude_value", "publicID"]
#time_window    = 4
#dist_threshold = 100.0