name: Python Package Tests

on:
  push:
    paths:
      - 'sievecomp/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'sievecomp/**'
      - 'tests/**'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the package in editable mode along with dev/example dependencies
          pip install -e .[dev,examples] pytest-cov

      - name: Run pytest
        env:
          # Ensures Python can find the 'sievecomp' module during execution
            PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/ -v --cov=sievecomp --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        if: always() # Ensures the report uploads even if some tests fail
        with:
            name: coverage-report
            path: coverage.xml
            retention-days: 14