name: Python Package Tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'

